apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "dd3cvc3r0"
  CLOUDINARY_API_KEY: "613625376311138"
  CLOUDINARY_API_SECRET: "EBDoyGQCy6nNY6Kw6CJdhXOZo2I"